### ISSUE TITLE
2.91 api 地址填写正确，无法连接服务器，本地黑群晖，套件Jellyfin10.7.6

### ISSUE THREAD

**Issue by zhshp2008** [gfriends/gfriends-inputer#1]
![image](https://user-images.githubusercontent.com/52740165/137486321-08826c52-1f70-41a3-9eae-fa0003af476f.png)
![image](https://user-images.githubusercontent.com/52740165/137486454-91348003-f662-45b6-9031-e2e24c894703.png)
求助

**Comment by xinxin8816** [comment]
新版本已解决此问题 [v3.00](https://github.com/gfriends/gfriends-inputer/releases)
