### ISSUE TITLE
连接 Gfriends 女友头像仓库超时，请检查网络连接

### ISSUE THREAD

**Issue by YangHgRi** [gfriends/gfriends-inputer#2]
开了代理,可以正常浏览GitHub
![image](https://user-images.githubusercontent.com/57426791/151392111-9d5989df-3c70-4a2f-9605-7855c6725397.png)

**Comment by xinxin8816** [comment]
新版本已解决此问题 [v3.00](https://github.com/gfriends/gfriends-inputer/releases)
