### ISSUE TITLE
网络访问无问题，但是，校验失败，可能是仓库收录的头像已损坏。

### ISSUE THREAD

**Issue by xmasrain** [gfriends/gfriends-inputer#22]
![image](https://user-images.githubusercontent.com/58833842/160427520-d7990817-d134-481b-8c0d-44fc316f29f0.png)

**Comment by xinxin8816** [comment]
新版本已修复偶现的校验失败问题 [v3.00](https://github.com/gfriends/gfriends-inputer/releases)
