### ISSUE TITLE
用域名连接jellyfin连接失败，配置了代理也会连接失败

### ISSUE THREAD

**Issue by 0987363** [gfriends/gfriends-inputer#31]
版本 ：2.91
系统：pve / debian 11

1、外网ddns配置的域名，内网adg上添加的域名映射到内网ip
不管是用外网的域名，还是内网的域名，都无法链接jellyfin，改用内网ip后连接正常
```
Gfriends Inputer v2.91
https://git.io/gfriends

[CN]中国四川 推荐开启全局代理

按任意键开始...
× 连接 Emby / Jellyfin 服务器失败，请检查地址是否正确： http://xxxxxx.com:9009/

× 用户强制停止或已知错误。
```

2、只要配置了代理，不管是http、socks5代理，代理方式不管是全局，还是repo，连接jellyfin都会失败，哪怕jellyfin配置的内网ip也会失败

代理确定是正常的，系统apt也使用的该代理

```
Gfriends Inputer v2.91
https://git.io/gfriends

[DE]德国黑森州 已连通局部代理 女友仓库经由代理连接

按任意键开始...
× 连接 Emby / Jellyfin 服务器失败，请检查地址是否正确： http://192.168.20.30:8096/

× 用户强制停止或已知错误。
```

这里是http代理日志
```
Oct 10 18:36:04 debian MEOW[14681]: [>>>>>] 2021/10/10 18:36:04 PROXY 192.168.20.30:48854 CONNECT api.myip.la:443
Oct 10 18:36:04 debian MEOW[14681]: [>>>>>] 2021/10/10 18:36:04 PROXY 192.168.20.30:48856 CONNECT api.github.com:443
```

**Comment by xinxin8816** [comment]
新版本已修复此问题 [v3.00](https://github.com/gfriends/gfriends-inputer/releases)

**Comment by 0987363** [comment]
今天有空用代码调试找到原因了。。
jellyfin时间久了会有卡顿，将验证api的请求超时改长，改为10s就正常了

另外有2个问题一起回复，新版3.01的
1. 获取public ip的时候不应该用线程，会出现还没获取到ip就进入下一步了
2. 不支持自签名证书，session应该增加 session.verify = False

**Comment by xinxin8816** [comment]
> 今天有空用代码调试找到原因了。。 jellyfin视频多了会有卡顿，比如我的Persons获取耗时9s多，获取到的json有5M 将获取Persons的请求超时改长，改为10s就正常了
> 
> 另外有2个问题一起回复，新版3.01的
> 
> 1. 获取public ip的时候不应该用线程，会出现还没获取到ip就进入下一步了
> 2. 不支持自签名证书，session应该增加 session.verify = False

Got it.
之后会适当调整超时时间、增加自签名适配
不过IP只是个提示，可有可无，没有必要堵塞主线程。

**Comment by xinxin8816** [comment]
另外之前的连不上的主要原因是代理写的有问题，导致有时DNS无法解析

**Comment by 0987363** [comment]
> 

没获取到ip的话，这里会panic
` logger.info('代理配置：' + str(proxies) + '，IP归属地：' + public_ip)`

**Comment by xinxin8816** [comment]
Ok，新版已修复这些潜在问题

0987363 ***@***.******@***.***>> 于2022年7月30日周六 11:44写道：

没获取到ip的话，这里会panic
logger.info<http://logger.info>('代理配置：' + str(proxies) + '，IP归属地：' + public_ip)

―
