### ISSUE TITLE
报错traceback <most recent last>:   File "Gfriends Inputer", Line 757,in <module>  NameError:name "inputed_dict" is no difined

### ISSUE THREAD

**Issue by tidus90** [gfriends/gfriends-inputer#37]
![QQ图片20220716084107](https://user-images.githubusercontent.com/95327156/179327486-4c9eaad7-ebd7-4151-a67d-9cea12fca0a5.png)
今天突然报错   不知道是什么问题.....

**Comment by xinxin8816** [comment]
尝试删除目录内的历史文件再试

**Comment by tidus90** [comment]
> 尝试删除目录内的历史文件再试
![QQ图片20220716134138](https://user-images.githubusercontent.com/95327156/179341624-b419cbfa-e426-450b-a1de-826d5ecd9ad7.png)删除后  再打开 显示没有需要下载导入的头像  但是我服务器里一个头像都没有............

**Comment by xinxin8816** [comment]
配置文件内选择`覆盖所有头像`

**Comment by tidus90** [comment]
> 配置文件内选择`覆盖所有头像`

你好  我选择不覆盖 和全部覆盖 就是出现米有需要下载和导入的头像  我选2 更新覆盖  就是最开始第一张图那个报错......我昨天用的挺好的  今天打开出的问题   是和MDC一起使用的

**Comment by xinxin8816** [comment]
经检查确实有此问题，现已修复，请重新下载 releases

**Comment by tidus90** [comment]
> 经检查确实有此问题，现已修复，请重新下载 releases

重新下载后问题解决     太感谢！
