### ISSUE TITLE
女友匹配错乱了。。。

### ISSUE THREAD

**Issue by cbingor** [gfriends/gfriends-inputer#43]
embyserver windows 4.7.5  
gi 3.02版本或者3.01版本 （可能是开了女友简介（xlist），不太确定）以后
影片对应 女优名字头像随机错乱（有些正确有些错误，之前整理的是完全正确的）
错乱表现为 原本影片对应的女友变成其他人了 
手动修改nfo无效（自动更新为另一个女优）
手动修改emby元数据无效（把错误的演员删除后 填写正确的演员名 会自动跳转到另外一个演员名）
不知道是不是emby数据库哪个表乱了
对非gi整理的演员无错误
例子1：
比如说abw-054  是凉森 然后emby显示的是美波什么的 把美波手动从元数据删除，填入凉森，存储，瞬间又跳转到美波
abw-054.nfo 里面  actor从凉森变成了美波（我重新用mdc搜刮后，再手动更改元数据凉森后又正确了，nfo复现错误失败）
例子2：
为了复现例子1的错误，没有再用mcd搜刮
abs-078 是朱音  变成另一个女优后手动更改成朱音ゆい 存储后 又变成宮下玲奈*（与第一次错误的女优不同） 
附上复现后abs-068.nfo

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<movie>
  <plot><![CDATA[ABS-078#『朱音结衣』跟两名男优前往兜风旅行。在旅馆的包租露天温泉就幹了起来，站立背后位合体，在寝室自慰后用肉棒猛插浑身师滑的身体高潮不已！]]></plot>
  <outline />
  <customrating>JP-18+</customrating>
  <lockdata>false</lockdata>
  <dateadded>2022-07-19 14:02:20</dateadded>
  <title>ABS-078 朱音ゆい 一泊二日、美少女完全予約制。 朱音ゆい</title>
  <originaltitle>ABS-078 朱音ゆい 一泊二日、美少女完全予約制。 朱音ゆい</originaltitle>
  <actor>
    <name>宮下玲奈</name>
    <type>Actor</type>
    <slistid>ot</slistid>
    <byid>friends:https://xslist.org/zh/model/5637.html</byid>
    <thumb>E:\embyserver\programdata\metadata\people\宮下玲奈\folder.jpg</thumb>
  </actor>
  <year>2012</year>
  <sorttitle>ABS-078 朱音ゆい 一泊二日、美少女完全予約制。 朱音ゆい</sorttitle>
  <mpaa>JP-18+</mpaa>
  <premiered>2012-02-20</premiered>
  <releasedate>2012-02-20</releasedate>
  <runtime>155</runtime>
  <genre>單體作品</genre>
  <genre>巨乳</genre>
  <genre>美少女</genre>
  <genre>一泊二日、美少女完全予約制。</genre>
  <genre>ABSOLUTE</genre>
  <studio>プレステージ</studio>
  <tag>單體作品</tag>
  <tag>巨乳</tag>
  <tag>美少女</tag>
  <tag>一泊二日、美少女完全予約制。</tag>
  <tag>ABSOLUTE</tag>
  <art>
    <poster>G:\色色\小日本子\abs-078\ABS-078-poster.jpg</poster>
    <fanart>G:\色色\小日本子\abs-078\ABS-078-fanart.jpg</fanart>
    <fanart>G:\色色\小日本子\abs-078\ABS-078-fanart.jpg</fanart>
    <fanart>G:\色色\小日本子\abs-078\extrafanart\extrafanart-1.jpg</fanart>
    <fanart>G:\色色\小日本子\abs-078\extrafanart\extrafanart-2.jpg</fanart>
    <fanart>G:\色色\小日本子\abs-078\extrafanart\extrafanart-3.jpg</fanart>
    <fanart>G:\色色\小日本子\abs-078\extrafanart\extrafanart-4.jpg</fanart>
    <fanart>G:\色色\小日本子\abs-078\extrafanart\extrafanart-5.jpg</fanart>
    <fanart>G:\色色\小日本子\abs-078\extrafanart\extrafanart-6.jpg</fanart>
  </art>
  <isuserfavorite>false</isuserfavorite>
  <playcount>0</playcount>
  <watched>false</watched>
  <resume>
    <position>0</position>
    <total>9313.842</total>
  </resume>
  <fileinfo>
    <streamdetails>
      <audio>
        <codec>wmapro</codec>
        <micodec>wmapro</micodec>
        <bitrate>384000</bitrate>
        <language>jpn</language>
        <scantype>progressive</scantype>
        <channels>2</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <video>
        <codec>vc1</codec>
        <micodec>vc1</micodec>
        <bitrate>3000000</bitrate>
        <width>1280</width>
        <height>720</height>
        <aspect>16:9</aspect>
        <aspectratio>16:9</aspectratio>
        <framerate>29.97003</framerate>
        <language>jpn</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
        <duration>155</duration>
        <durationinseconds>9313</durationinseconds>
      </video>
    </streamdetails>
  </fileinfo>
  <poster>ABS-078-poster.jpg</poster>
  <thumb>ABS-078-thumb.jpg</thumb>
  <fanart>ABS-078-fanart.jpg</fanart>
  <maker>プレステージ</maker>
  <label>一泊二日、美少女完全予約制。</label>
  <num>ABS-078</num>
  <release>2012-02-20</release>
  <cover>https://www.javbus.com/pics/cover/3u51_b.jpg</cover>
  <website>https://www.javbus.com/ABS-078</website>
</movie>

**Comment by xinxin8816** [comment]
能不能排版一下，我难以阅读你的文字

**Comment by xinxin8816** [comment]
Gfriends Inputer 不会修改 nfo，你上述提及的几个女友我测试都没问题

**Comment by cbingor** [comment]
环境：embyserver windows 4.7.5
版本：gi 3.02版本或者3.01版本 （可能是开了女友简介（xlist），不太确定）
错误：影片对应 女优名字头像随机错乱（有些正确有些错误，之前整理的是完全正确的）
表现： 原本影片对应的女友随机变成其他人了
手动修改nfo无效：自动更新为另一个女优）
手动修改emby元数据无效：把错误的演员删除后 填写正确的演员名 会自动跳转到另外一个演员名）
不知道是不是emby数据库哪个表乱了
对非gi整理的演员无错误
例子1：
比如说abw-054 是凉森 然后emby显示的是美波什么的
 把美波手动从元数据删除，填入凉森，存储，瞬间又跳转到美波
abw-054.nfo 里面 actor从凉森变成了美波
（我重新用mdc搜刮后，再手动更改元数据凉森后又正确了，nfo复现错误失败）
例子2：
为了复现例子1的错误，没有再用mcd搜刮
abs-078 是朱音 变成另一个女优后手动更改成朱音ゆい 存储后 又变成宮下玲奈*（与第一次错误的女优不同）

re:Gfriends Inputer 不会修改 nfo，你上述提及的几个女友我测试都没问题
这几天一直用gi在搜刮头像，2.94之前片库都是正确的，就这两天更新了3.01和3.02以后（一开始没注意，大可能是3.02，今天才发现的），才出现数据库错乱。
不是说gi修改的nfo，而是在已经错乱的情况下，通过emby修改元数据后会自动跳转到另外的女优，会不会是gi在添加people库的时候造出来的表有个什么错误。。

**Comment by cbingor** [comment]
> Gfriends Inputer 不会修改 nfo，你上述提及的几个女友我测试都没问题

上面回复。。不大会用github的回复

**Comment by xinxin8816** [comment]
Gfriends Inputer 完全使用 Emby 的 API 来操作媒体库演员信息，不会凭空造出来数据表。另外关闭程序后，就不会对 Emby 有任何进一步修改了。
你的情况可能是什么插件在操作媒体库。

**Comment by cbingor** [comment]
> Gfriends Inputer 完全使用 Emby 的 API 来操作媒体库演员信息，不会凭空造出来数据表。另外关闭程序后，就不会对 Emby 有任何进一步修改了。 你的情况可能是什么插件在操作媒体库。

进一步发现一个问题，多出来好几个不存在的女优（就是我片库没有的，认真校对过，确实这几人不存在，本身我片下的不多）
然后emby环境吧。。。确实没装啥多余的插件。。。就一个豆瓣不是默认插件T_T

**Comment by xinxin8816** [comment]
不会出现增加女友的情况，Inputer 只修改现有女友，且不会修改姓名。

**Comment by xinxin8816** [comment]
Griends Inputer 配置文件开启 DEBUG 模式，重新运行一遍程序然后把 Getter 目录下的 logger.log 日志作为附件发上来。

**Comment by cbingor** [comment]
> Griends Inputer 配置文件开启 DEBUG 模式，重新运行一遍程序然后把 Getter 目录下的 logger.log 日志作为附件发上来。

好的
[logger.log](https://github.com/gfriends/gfriends-inputer/files/9228687/logger.log)

**Comment by xinxin8816** [comment]
显然有插件或其他程序修改了你的演员信息，甚至把 Inputer 上次导入的头像都覆盖了。

**Comment by xinxin8816** [comment]
你提到豆瓣不是默认插件，值得注意的是 Emby 的插件并不需要配置到媒体库中，只要安装了便有权限修改演员信息。

**Comment by cbingor** [comment]
> 你提到豆瓣不是默认插件，值得注意的是 Emby 的插件并不需要配置到媒体库中，只要安装了便有权限修改演员信息。

我仔細看了下emby的programdata，有個半年前卸载的javstrip的配置文件还在（本体dl已经删除了半年），然後小黃片的媒体库其实都沒配置搜刮器的，所有搜刮器選項都是空的,剛才亂了，我還特意把庫刪了，重新新建來的，奇怪了

**Comment by cbingor** [comment]
> 你提到豆瓣不是默认插件，值得注意的是 Emby 的插件并不需要配置到媒体库中，只要安装了便有权限修改演员信息。

现在正在用movie data captrue重建媒体库nfo，完成后我再回报下情况

**Comment by xinxin8816** [comment]
> > 你提到豆瓣不是默认插件，值得注意的是 Emby 的插件并不需要配置到媒体库中，只要安装了便有权限修改演员信息。
> 
> 我仔細看了下emby的programdata，有個半年前卸载的javstrip的配置文件还在（本体dl已经删除了半年），然後小黃片的媒体库其实都沒配置搜刮器的，所有搜刮器選項都是空的,剛才亂了，我還特意把庫刪了，重新新建來的，奇怪了

虽然没配置刮削器，但只要安装了，它就有权限修改演员信息，这和影片信息不一样。

**Comment by cbingor** [comment]
> > > 你提到豆瓣不是默认插件，值得注意的是 Emby 的插件并不需要配置到媒体库中，只要安装了便有权限修改演员信息。
> > 
> > 
> > 我仔細看了下emby的programdata，有個半年前卸载的javstrip的配置文件还在（本体dl已经删除了半年），然後小黃片的媒体库其实都沒配置搜刮器的，所有搜刮器選項都是空的,剛才亂了，我還特意把庫刪了，重新新建來的，奇怪了
> 
> 虽然没配置刮削器，但只要安装了，它就有权限修改演员信息，这和影片信息不一样。

额  后来清理了emby数据库 恢复正常了

**Comment by blitzzzzz** [comment]
> Gfriends Inputer 完全使用 Emby 的 API 来操作媒体库演员信息，不会凭空造出来数据表。另外关闭程序后，就不会对 Emby 有任何进一步修改了。
> 你的情况可能是什么插件在操作媒体库。



> > > 你提到豆瓣不是默认插件，值得注意的是 Emby 的插件并不需要配置到媒体库中，只要安装了便有权限修改演员信息。
> > 
> > 
> > 我仔細看了下emby的programdata，有個半年前卸载的javstrip的配置文件还在（本体dl已经删除了半年），然後小黃片的媒体库其实都沒配置搜刮器的，所有搜刮器選項都是空的,剛才亂了，我還特意把庫刪了，重新新建來的，奇怪了
> 
> 虽然没配置刮削器，但只要安装了，它就有权限修改演员信息，这和影片信息不一样。

我在添加女友简介后也碰到这个问题了

开了全新emby docker，新数据库，只有默认插件，排查到和nfo文件中`<gfriendsid>https://git.io/gfriends</gfriendsid>`这个标签有关联。把这行删了再重新导入影片就正常了。
并不是增加女友或者修改女友名字，而是把很多电影关联到某1个无关的已存在的女友名下，影片页面显示错误女友，女友页面也显示这个错误的影片

可能emby不能正确处理这个标签，这时emby内置数据库里女友错乱了。然后有时候我会用emby编辑了元数据（加标签）就会写入到nfo文件。
nfo文件里有这个标签的影片再导入到干净的emby（没有导入过女友头像和简介）也还是错误的
希望这信息能有用
<img width="406" alt="截屏2023-02-02 13 31 09" src="https://user-images.githubusercontent.com/8655944/216240620-d3e667e8-68c5-4e3c-8e01-db8f66f998ac.png">
[MIDV-062-C.nfo.txt](https://github.com/gfriends/gfriends-inputer/files/10565307/MIDV-062-C.nfo.txt)

**Comment by xinxin8816** [comment]
> > Gfriends Inputer 完全使用 Emby 的 API 来操作媒体库演员信息，不会凭空造出来数据表。另外关闭程序后，就不会对 Emby 有任何进一步修改了。
> > 你的情况可能是什么插件在操作媒体库。
> 
> > > > 你提到豆瓣不是默认插件，值得注意的是 Emby 的插件并不需要配置到媒体库中，只要安装了便有权限修改演员信息。
> > > 
> > > 
> > > 我仔細看了下emby的programdata，有個半年前卸载的javstrip的配置文件还在（本体dl已经删除了半年），然後小黃片的媒体库其实都沒配置搜刮器的，所有搜刮器選項都是空的,剛才亂了，我還特意把庫刪了，重新新建來的，奇怪了
> > 
> > 
> > 虽然没配置刮削器，但只要安装了，它就有权限修改演员信息，这和影片信息不一样。
> 
> 我在添加女友简介后也碰到这个问题了
> 
> 开了全新emby docker，新数据库，只有默认插件，排查到和nfo文件中`<gfriendsid>https://git.io/gfriends</gfriendsid>`这个标签有关联。把这行删了再重新导入影片就正常了。 并不是增加女友或者修改女友名字，而是把很多电影关联到某1个无关的已存在的女友名下，影片页面显示错误女友，女友页面也显示这个错误的影片
> 
> 可能emby不能正确处理这个标签，这时emby内置数据库里女友错乱了。然后有时候我会用emby编辑了元数据（加标签）就会写入到nfo文件。 nfo文件里有这个标签的影片再导入到干净的emby（没有导入过女友头像和简介）也还是错误的 希望这信息能有用 <img alt="截屏2023-02-02 13 31 09" width="406" src="https://user-images.githubusercontent.com/8655944/216240620-d3e667e8-68c5-4e3c-8e01-db8f66f998ac.png"> [MIDV-062-C.nfo.txt](https://github.com/gfriends/gfriends-inputer/files/10565307/MIDV-062-C.nfo.txt)

Gfriends Inputer 只会也只能修改数据库的 Person 演员相关条目，它无权修改影片 NFO 文件。
根据目前已知的情报，<gfriendsid>字段是由 JavScraper 插件写入的。

**Comment by blitzzzzz** [comment]
> > > Gfriends Inputer 完全使用 Emby 的 API 来操作媒体库演员信息，不会凭空造出来数据表。另外关闭程序后，就不会对 Emby 有任何进一步修改了。
> > > 你的情况可能是什么插件在操作媒体库。
> > 
> > 
> > > > > 你提到豆瓣不是默认插件，值得注意的是 Emby 的插件并不需要配置到媒体库中，只要安装了便有权限修改演员信息。
> > > > 
> > > > 
> > > > 我仔細看了下emby的programdata，有個半年前卸载的javstrip的配置文件还在（本体dl已经删除了半年），然後小黃片的媒体库其实都沒配置搜刮器的，所有搜刮器選項都是空的,剛才亂了，我還特意把庫刪了，重新新建來的，奇怪了
> > > 
> > > 
> > > 虽然没配置刮削器，但只要安装了，它就有权限修改演员信息，这和影片信息不一样。
> > 
> > 
> > 我在添加女友简介后也碰到这个问题了
> > 开了全新emby docker，新数据库，只有默认插件，排查到和nfo文件中`<gfriendsid>https://git.io/gfriends</gfriendsid>`这个标签有关联。把这行删了再重新导入影片就正常了。 并不是增加女友或者修改女友名字，而是把很多电影关联到某1个无关的已存在的女友名下，影片页面显示错误女友，女友页面也显示这个错误的影片
> > 可能emby不能正确处理这个标签，这时emby内置数据库里女友错乱了。然后有时候我会用emby编辑了元数据（加标签）就会写入到nfo文件。 nfo文件里有这个标签的影片再导入到干净的emby（没有导入过女友头像和简介）也还是错误的 希望这信息能有用 <img alt="截屏2023-02-02 13 31 09" width="406" src="https://user-images.githubusercontent.com/8655944/216240620-d3e667e8-68c5-4e3c-8e01-db8f66f998ac.png"> [MIDV-062-C.nfo.txt](https://github.com/gfriends/gfriends-inputer/files/10565307/MIDV-062-C.nfo.txt)
> 
> Gfriends Inputer 只会也只能修改数据库的 Person 演员相关条目，它无权修改影片 NFO 文件。 根据目前已知的情报，字段是由 JavScraper 插件写入的。

额，我没用过这个插件，测试的环境是干净docker镜像。我的意思不是谁把这个标签写到nfo文件里，而是emby遇到这个标签似乎有问题。大佬能不能测试下

**Comment by xinxin8816** [comment]
> > > > Gfriends Inputer 完全使用 Emby 的 API 来操作媒体库演员信息，不会凭空造出来数据表。另外关闭程序后，就不会对 Emby 有任何进一步修改了。
> > > > 你的情况可能是什么插件在操作媒体库。
> > > 
> > > 
> > > > > > 你提到豆瓣不是默认插件，值得注意的是 Emby 的插件并不需要配置到媒体库中，只要安装了便有权限修改演员信息。
> > > > > 
> > > > > 
> > > > > 我仔細看了下emby的programdata，有個半年前卸载的javstrip的配置文件还在（本体dl已经删除了半年），然後小黃片的媒体库其实都沒配置搜刮器的，所有搜刮器選項都是空的,剛才亂了，我還特意把庫刪了，重新新建來的，奇怪了
> > > > 
> > > > 
> > > > 虽然没配置刮削器，但只要安装了，它就有权限修改演员信息，这和影片信息不一样。
> > > 
> > > 
> > > 我在添加女友简介后也碰到这个问题了
> > > 开了全新emby docker，新数据库，只有默认插件，排查到和nfo文件中`<gfriendsid>https://git.io/gfriends</gfriendsid>`这个标签有关联。把这行删了再重新导入影片就正常了。 并不是增加女友或者修改女友名字，而是把很多电影关联到某1个无关的已存在的女友名下，影片页面显示错误女友，女友页面也显示这个错误的影片
> > > 可能emby不能正确处理这个标签，这时emby内置数据库里女友错乱了。然后有时候我会用emby编辑了元数据（加标签）就会写入到nfo文件。 nfo文件里有这个标签的影片再导入到干净的emby（没有导入过女友头像和简介）也还是错误的 希望这信息能有用 <img alt="截屏2023-02-02 13 31 09" width="406" src="https://user-images.githubusercontent.com/8655944/216240620-d3e667e8-68c5-4e3c-8e01-db8f66f998ac.png"> [MIDV-062-C.nfo.txt](https://github.com/gfriends/gfriends-inputer/files/10565307/MIDV-062-C.nfo.txt)
> > 
> > 
> > Gfriends Inputer 只会也只能修改数据库的 Person 演员相关条目，它无权修改影片 NFO 文件。 根据目前已知的情报，字段是由 JavScraper 插件写入的。
> 
> 额，我没用过这个插件，测试的环境是干净docker镜像。我的意思不是谁把这个标签写到nfo文件里，而是emby遇到这个标签似乎有问题。大佬能不能测试下

如果你在干净环境测试能复现问题，建议去 [Emby 社区](https://emby.media/community/) 找 Luke 反馈。
