### ISSUE TITLE
信息导入问题

### ISSUE THREAD

**Issue by tolancs** [gfriends/gfriends-inputer#45]
Jellyfin导入没有适配，导入失败

**Comment by xinxin8816** [comment]
请上传日志

**Comment by 553531284** [comment]
当前格式：
{
    'Name': name,
    'ProviderIds': 'XSlist got by gfriends:' + detial_url,
    'Taglines': ['日本AV女优'],
    'Overview': detial_info
}

Jellyfin（版本10.8.1）测试可正常录入格式：		   
{
    "Name": "天川そら",
    "ProviderIds": {"XSlist":"60714"},
	"ExternalUrls": [
        {
            "Name": "XSlist",
            "Url": "https://xslist.org/zh/model/60714.html"
        }
    ],
    "Taglines": ["日本AV女优"],
    "Genres": [],
    "Tags": ["日本AV女优"],
    "Overview": "出生: 1998年10月09日<br>三围: B86 / W56 / H84<br>罩杯: F Cup<br>出道日期: 2019年10月<br>星座: Libra<br>血型: n/a<br>身高: 164cm<br>国籍: 日本<br><br>"
}


ProviderIds 格式不正确。正确也没太大作用，没什么效果。（测了下相关字段ExternalUrls没用，不管他。）
Taglines 这个字段接口是可以接收，但Tags字段才有效果。
ProviderIds、Genres、Tags这几个必穿，即使他是空的。

**Comment by xinxin8816** [comment]
@553531284 抽空处理，你测试没问题也可以直接 PR 源码

**Comment by xinxin8816** [comment]
[v3.03](https://github.com/gfriends/gfriends-inputer/releases) 修复了 Jellyfin 导入信息的兼容问题

**Comment by tolancs** [comment]
Code 没改啊

**Comment by xinxin8816** [comment]
@tolancs [v3.04](https://github.com/gfriends/gfriends-inputer/releases/tag/v3.04) 修复了 Jellyfin10.8 导入信息的问题
