### ISSUE TITLE
503报错

### ISSUE THREAD

**Issue by tyujrtuy** [gfriends/gfriends-inputer#46]
[HK]中国香港 已连通局部代理

× 连接 Emby / Jellyfin 服务器成功，但是服务器内部错误：503
× 已知错误，请查阅 Getter 目录的 logger.log 日志文件。
按任意键退出程序...

3.02版本

**Comment by tyujrtuy** [comment]
[logger.log](https://github.com/gfriends/gfriends-inputer/files/9277683/logger.log)

**Comment by xinxin8816** [comment]
媒体服务器什么版本？

**Comment by tyujrtuy** [comment]
4750

**Comment by xinxin8816** [comment]
这个错误是媒体服务器出了问题，也可能是服务器地址写错了

**Comment by tyujrtuy** [comment]
![image](https://user-images.githubusercontent.com/108184767/183329069-8a912164-8975-4272-ad71-d41104011523.png)
没问题吧这。。

**Comment by xinxin8816** [comment]
host_url + emby/Persons?api_key= + api_key
替换地址和密匙后用浏览器访问，看看返回什么结果

**Comment by tyujrtuy** [comment]
![image](https://user-images.githubusercontent.com/108184767/183336331-5526c707-8d48-423a-bb5f-e18d1f85869d.png)
我换了api，没换端口报这个直接闪退

**Comment by tyujrtuy** [comment]
[config.zip](https://github.com/gfriends/gfriends-inputer/files/9278591/config.zip)
你看下config有啥问题没

**Comment by tyujrtuy** [comment]
服务器地址无论是192还是http://localhost:8096/都一样

**Comment by tyujrtuy** [comment]
[logger.log](https://github.com/gfriends/gfriends-inputer/files/9278633/logger.log)
重装sever后不闪退了但是还是进不去

**Comment by xinxin8816** [comment]
试下关闭配置文件中的代理，然后用你的代理软件全局代理
________________________________

**Comment by tyujrtuy** [comment]
OK了
