### ISSUE TITLE
3.02版本的代理模块太傻了

### ISSUE THREAD

**Issue by harvey-git** [gfriends/gfriends-inputer#47]
不指定代理，则连不上头像仓库，但是连jellyfin的服务器没问题；
指定代理，能连上头像仓库了，但是连不上jellyfin的服务器了；
最后我不的不翻源码，翻到仓库的网址，跑到路由器上去加区旁路仓库地址到红杏上。
2.94版本就没有这个问题，会自动旁路内网（jellyfin服务器）地址。

**Comment by Marce1ek** [comment]
说点人话吧😀

**Comment by xinxin8816** [comment]
老版本的代理实现有兼容性问题😢
你的路由器太傻了不会自动分流🤣
________________________________
