### ISSUE TITLE
女优信息无法搜索导入

### ISSUE THREAD

**Issue by kingfxx** [gfriends/gfriends-inputer#50]
头像下载导入正常,但是女优信息无法搜索导入,代理已开,全局和非全局都试过,log里面也没有相关提示

**Comment by xinxin8816** [comment]
打开debug才会有具体日志

**Comment by xinxin8816** [comment]
[v3.03](https://github.com/gfriends/gfriends-inputer/releases) 修复了 Jellyfin 导入信息的兼容问题

**Comment by xinxin8816** [comment]
[v3.04](https://github.com/gfriends/gfriends-inputer/releases/tag/v3.04) 修复了 Jellyfin10.8 导入信息的问题
