### ISSUE TITLE
设置搜索女友个人信息，但在jellyfin中没有显示

### ISSUE THREAD

**Issue by mark5231** [gfriends/gfriends-inputer#55]
![image](https://user-images.githubusercontent.com/91494227/204106650-9afc6911-458a-4eff-b24b-e824cfbd0fdf.png)

所有的女友信息都如上图所示

**Comment by xinxin8816** [comment]
打开 debug 重新导入，然后把 Getter 目录下的 logger.log 日志上传到这里

**Comment by mark5231** [comment]
> 打开 debug 重新导入，然后把 Getter 目录下的 logger.log 日志上传到这里

[logger.log](https://github.com/gfriends/gfriends-inputer/files/10106396/logger.log)

**Comment by xinxin8816** [comment]
之后会修复这个问题

**Comment by xinxin8816** [comment]
[v3.04](https://github.com/gfriends/gfriends-inputer/releases/tag/v3.04) 修复了 Jellyfin10.8 导入信息的问题
