### ISSUE TITLE
Debian 11 运行报错

### ISSUE THREAD

**Issue by Rebuilding127** [gfriends/gfriends-inputer#60]
报错如下：
[68975] Error loading Python lib '/tmp/_MEIK88ttI/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIK88ttI/libpython3.9.so.1.0)

运行环境：
Debian 11
gfriends-inputer 3.04
系统和软件都是最新下载的

查阅到之前有人提交issues，回复说是系统Glibc库到2.29或以上版本。
我自己查了下Glibc库版本`ldd --version` 输出如下：

ldd (Debian GLIBC 2.31-13+deb11u5) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

版本上应该是符合要求的，不知是提高了版本要求，还是别的问题导致？

**Comment by xinxin8816** [comment]
Hi，现在提高了版本要求，需要Glibc库到2.35或以上版本
如果不想升级Glibc库，也可以直接运行源码
