### ISSUE TITLE
求大佬给个群晖部署教程

### ISSUE THREAD

**Issue by kejiaxiaoyangtuo** [gfriends/gfriends-inputer#61]
群晖小白，实在是不会部署这个，能教教我吗。在群晖docker中找到两个和这个一摸一样的链接，下载下来不知道怎么配置。求大佬给个群晖部署教程，万分感谢

**Comment by xinxin8816** [comment]
群辉可以直接在终端中运行二进制文件，亦或者运行源码

目前官方没有docker镜像
